
macro(get_file_io_handler_version FIOH_VERSION_PLAIN)
    SET(FILE_IO_HANDLER_VERSION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/src/version.hpp")
    file(STRINGS "${FILE_IO_HANDLER_VERSION_FILE}" FIOH_VERSION_PARTS REGEX "#define FIOH_VERSION_[A-Z]+[ ]+" )

    string(REGEX REPLACE ".+FIOH_VERSION_MAJOR[ ]+([0-9]+).*" "\\1" FIOH_VERSION_MAJOR "${FIOH_VERSION_PARTS}")
    string(REGEX REPLACE ".+FIOH_VERSION_MINOR[ ]+([0-9]+).*" "\\1" FIOH_VERSION_MINOR "${FIOH_VERSION_PARTS}")
    string(REGEX REPLACE ".+FIOH_VERSION_REVISION[ ]+([0-9]+).*" "\\1" FIOH_VERSION_PATCH "${FIOH_VERSION_PARTS}")
    string(REGEX REPLACE ".+FIOH_VERSION_STATUS[ ]+\"([^\"]*)\".*" "\\1" FIOH_VERSION_STATUS "${FIOH_VERSION_PARTS}")

    set(FIOH_VERSION_PLAIN "${FIOH_VERSION_MAJOR}.${FIOH_VERSION_MINOR}.${FIOH_VERSION_PATCH}")
    set(FIOH_VERSION_FULL "${FIOH_VERSION_MAJOR}.${FIOH_VERSION_MINOR}.${FIOH_VERSION_PATCH}_${FIOH_VERSION_STATUS}")
    message("FileIoHandler Version: " ${FIOH_VERSION_FULL})
endmacro()
